brew cask install flux
brew cask install google-chrome
brew cask install vlc
brew cask install github-desktop
brew cask install appcleaner
brew cask install docker
brew cask install github-desktop
brew cask install iterm2
brew cask install kap
brew cask install messenger
brew cask install nordvpn
brew cask install postico
brew cask install postman
brew cask install skype
brew cask install slack
brew cask install spotify
brew cask install transmission
brew cask install visual-studio-code